# Site settings
# {{ site.title }}
title: SMixqse
description: O site oficial do SMixqse.
baseurl: ""
url: "https://smixqse.ga"

# Build settings
markdown: kramdown

# Variables
twitter: smixqse
yt1name: SMix
yt1link: https://www.youtube.com/channel/UCMsLB-9AECak7w_K9Z6OrBw
yt2name: MixPoops
yt2link: https://www.youtube.com/channel/UCXlnLNV8VjHU8A18C8Gal3w
discord: smixqse#9658
discordserver1: https://discord.gg/YJDntMT
discordserver2: https://discord.gg/5q6t9SN
github: smixqse
spotify: loukky-br